name: Unit tests

on: [pull_request, push]

env:
  NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  ci-unit-tests:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: printenv
      - uses: actions/setup-node@v4
        with:
          # This should match the using value in `actions.yaml`
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@fond-of'
      - run: npm ci
      - run: npm run lint
